### ISSUE TITLE
Feature: Create an option to enter value into the field

### ISSUE THREAD

**Issue by aswinikalyan30** [KiranAminPanjwani/Tracker-Expense-Calculator#3]
Sometimes it is difficult to adjust the slider to the correct value, so there should be an option to enter value instead

**Comment by KiranAminPanjwani** [comment]
Don't remove the sliders. Instead, make these input fields editable. 😊

![image](https://user-images.githubusercontent.com/90326051/193878285-134484fc-4b38-4bd2-b842-0cae3590021b.png)

**Comment by aswinikalyan30** [comment]
Yes, I want to do that.
